import "./globals.css";


export const metadata = {
  title: "Barbary POS",
  description: "Generated by Rockai Dev",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar">
      <body className="h-screen relative flex font-mainFont" suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  );
}
